export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_HOURS_SUCCESS = 'FETCH_HOURS_SUCCESS';
export const SET_HOURS_SUCCESS = 'SET_HOURS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
